#!/bin/sh -e
# initramfs hook for intel

MINKVER="2.6.17"
PREREQ=""

# Output pre-requisites
prereqs()
{
	echo "$PREREQ"
}

case "$1" in
    prereqs)
	prereqs
	exit 0
	;;
esac


. /usr/share/initramfs-tools/hook-functions

# Add used commands
mkdir -p ${DESTDIR}/usr/bin
mkdir -p ${DESTDIR}/usr/lib/xorg/modules/drivers
mkdir -p ${DESTDIR}/usr/lib/dri
mkdir -p ${DESTDIR}/usr/share/xserver-xorg/pci

# Copy needed files
copy_exec /usr/lib/xorg/modules/drivers/intel_drv.so /usr/lib/xorg/modules/drivers
copy_exec /usr/lib/xorg/modules/drivers/ch7xxx.so /usr/lib/xorg/modules/drivers
copy_exec /usr/lib/xorg/modules/drivers/ch7017.so /usr/lib/xorg/modules/drivers
copy_exec /usr/lib/xorg/modules/drivers/tfp410.so /usr/lib/xorg/modules/drivers
copy_exec /usr/lib/xorg/modules/drivers/ivch.so /usr/lib/xorg/modules/drivers
copy_exec /usr/lib/xorg/modules/drivers/sil164.so /usr/lib/xorg/modules/drivers
copy_exec /usr/share/xserver-xorg/pci/intel.ids /usr/share/xserver-xorg/pci
copy_exec /usr/lib/libIntelXvMC.so /usr/lib
copy_exec /usr/lib/libI810XvMC.so /usr/lib
copy_exec /usr/lib/dri/i915_dri.so /usr/lib/dri
copy_exec /usr/lib/dri/i965_dri.so /usr/lib/dri
